# Generated by Django 2.2.6 on 2019-12-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_team_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
