# Generated by Django 3.0 on 2019-12-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_team_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team')),
            ],
        ),
    ]
