# Generated by Django 3.0 on 2019-12-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team1_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team2_complete',
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='whoAndWhat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='whoAndWhat',
            field=models.ManyToManyField(to='main_app.whoAndWhat'),
        ),
    ]
