# Generated by Django 3.0 on 2019-12-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191229_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoandwhat',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
        ),
    ]
