# Generated by Django 3.0 on 2019-12-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191229_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='winner',
        ),
        migrations.AlterField(
            model_name='whoandwhat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
        ),
        migrations.CreateModel(
            name='MatchAndWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(default='False')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Match')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='matchAndWinner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.MatchAndWinner'),
            preserve_default=False,
        ),
    ]
