# Generated by Django 2.2.6 on 2019-12-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191223_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
