# Generated by Django 2.2.6 on 2019-12-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191223_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
