# Generated by Django 2.2.6 on 2019-12-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_1_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='team_2_complete',
            field=models.BooleanField(default=False),
        ),
    ]
