# Generated by Django 3.0 on 2019-12-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191231_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
