# Generated by Django 2.2.6 on 2019-12-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191220_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
    ]
