# Generated by Django 3.0 on 2019-12-31 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_team_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='match',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
        migrations.AddField(
            model_name='whoandwhat',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoandwhat',
            name='task_number',
            field=models.IntegerField(default=-1),
        ),
    ]
