# Generated by Django 2.2.6 on 2020-01-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191231_1900'),
        ('main_app', '0002_auto_20191231_2007'),
    ]

    operations = [
    ]
