# Generated by Django 2.2.6 on 2019-12-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='judge',
        ),
    ]
