# Generated by Django 2.2.6 on 2020-01-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20200101_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_1_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_2_complete',
        ),
    ]
