# Generated by Django 2.2.6 on 2020-01-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200101_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
            preserve_default=False,
        ),
    ]
