# Generated by Django 2.2.6 on 2019-12-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191223_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='team',
        ),
    ]
