# Generated by Django 2.2.6 on 2020-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_team_matchandwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_1_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='team_2_complete',
            field=models.BooleanField(default=False),
        ),
    ]
