# Generated by Django 2.2.6 on 2019-12-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_photo_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
            preserve_default=False,
        ),
    ]
