# Generated by Django 2.2.6 on 2020-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200101_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='whoAndWhat',
        ),
        migrations.AlterField(
            model_name='task',
            name='team_1_complete',
            field=models.BooleanField(choices=[(True, False)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_2_complete',
            field=models.BooleanField(choices=[(True, False)]),
        ),
    ]
