# Generated by Django 2.2.6 on 2020-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200101_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(to='main_app.Team'),
        ),
    ]
