# Generated by Django 2.2.6 on 2019-12-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photo_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='team',
        ),
    ]
