# Generated by Django 2.2.6 on 2020-01-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_team_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
    ]
