# Generated by Django 3.0 on 2020-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team_1_complete',
            field=models.BooleanField(choices=[(True, False)], default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_2_complete',
            field=models.BooleanField(choices=[(True, False)], default=False),
        ),
    ]
