# Generated by Django 3.0 on 2020-01-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200102_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoandwhat',
            name='task_number',
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=-1),
        ),
    ]
