# Generated by Django 3.0 on 2020-01-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200102_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchAndWinner',
        ),
    ]
