# Generated by Django 3.0.2 on 2020-01-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_team_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_1_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_2_complete',
        ),
        migrations.RemoveField(
            model_name='whoandwhat',
            name='match',
        ),
        migrations.AddField(
            model_name='task',
            name='whoAndWhat',
            field=models.ManyToManyField(default=None, to='main_app.WhoAndWhat'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whoandwhat',
            name='complete',
            field=models.BooleanField(choices=[(True, False)], default=False),
        ),
    ]
